# Generated by Django 3.2.6 on 2021-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210804_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nesting_level',
            field=models.IntegerField(default=0),
        ),
    ]
